config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tournaments

  root to: 'tournaments#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
# frozen_string_literal: true

class Division < ApplicationRecord
  belongs_to :tournament
  belongs_to :team
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :a_team
  belongs_to :b_team
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
  DRAFT       = 1
  IN_PROGRESS = 2
  DONE        = 3

  STATUSES = {
    DRAFT => 'draft',
    IN_PROGRESS => 'in_progress',
    DONE => 'done'
  }.freeze

  validates :name, uniqueness: true
  validates :name, presence: true, allow_blank: false
  validates :status, inclusion: { in: STATUSES.keys,
                                  message: "must be one of: [ #{STATUSES.values.join ', '} ]" }

  def status_name
    STATUSES[status]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[show edit update destroy]

  # GET /tournaments or /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1 or /tournaments/1.json
  def show; end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
    @teams = 16.times.map { Faker::Lorem.unique.words(number: 3).join(' ').capitalize }
  end

  # GET /tournaments/1/edit
  def edit; end

  # POST /tournaments or /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournament_url(@tournament), notice: t('tournaments.successfully_created') }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1 or /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_url(@tournament), notice: t('tournaments.successfully_updated') }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1 or /tournaments/1.json
  def destroy
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: t('tournaments.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tournament_params
    params.require(:tournament).permit(:name, :games)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tournaments_helper.rb
# frozen_string_literal: true

module TournamentsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Tournament
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')
    = javascript_include_tag('application', 'data-turbolinks-track': 'reload')

  body
    == yield

app/views/tournaments/_form.html.slim
= form_for @tournament do |f|
  - if @tournament.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tournament.errors.count, "error")} prohibited this tournament from being saved:"
    ul
      - @tournament.errors.full_messages.each do |message|
        li = message

  .field
    = f.label :name
    = f.text_field :name

  .actions = f.submit

app/views/tournaments/_teams.html.slim
ul
  - @teams.each do | team |
    li  = team

app/views/tournaments/edit.html.slim
h1 Editing tournament

== render "form"

=> link_to "Show", @tournament
'|
=< link_to "Back", tournaments_path

app/views/tournaments/index.html.slim
h1 Listing tournaments

table
  thead
    tr
      th Name
      th Status
      th
      th

  tbody
    - @tournaments.each do |tournament|
      tr
        td = tournament.name
        td = tournament.status_name
        td = link_to "Show", tournament
        td = link_to "Edit", edit_tournament_path(tournament)
        td = link_to "Destroy", tournament, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Tournament", new_tournament_path

app/views/tournaments/new.html.slim
h1 New tournament

== render "teams", teams: @teams
== render "form"

= link_to "Back", tournaments_path

app/views/tournaments/show.html.slim
p#notice = notice

p
  strong Name:
  = @tournament.name
p
  strong Status:
  = @tournament.status_name

p
  strong Divisions:


=> link_to "Edit", edit_tournament_path(@tournament)
'|
=< link_to "Back", tournaments_path